'use client';
import { useState, useEffect, useLayoutEffect, useRef, useCallback } from 'react';
import { move } from '../lib/engine.mjs';
const labels = { ksiva: 'КСИВА', shadow: 'КСИВА', past: 'КСИВА · ТОГДА', stranger: 'КТО-ТО · ТОГДА', radio: 'КОММУНИКАТОР' };
export default function Novel({ frames }) {
  const [index, setIndex] = useState(0), [count, setCount] = useState(0), [sound, setSound] = useState(false), [panel, setPanel] = useState(null), [ended, setEnded] = useState(false), [ready, setReady] = useState(false);
  const audio = useRef(null), modal = useRef(null);
  const frame = frames[index];
  useEffect(() => { try { const n = Number(localStorage.getItem('ksiva-position-v1')); if(Number.isInteger(n) && n >= 0 && n < frames.length) setIndex(n); } catch {} setReady(true); }, [frames.length]);
  useEffect(() => { if (ready) { try { localStorage.setItem('ksiva-position-v1', String(index)); } catch {} } }, [index, ready]);
  // Reset before paint so a new line never uses the previous line's reveal count.
  useLayoutEffect(() => { setCount(window.matchMedia('(prefers-reduced-motion: reduce)').matches ? frame.text.length : 0); }, [index, frame.text]);
  useEffect(() => { if (count >= frame.text.length || panel || ended) return; const timer = setTimeout(() => setCount(c => c + 2), 24); return () => clearTimeout(timer); }, [index, count, frame.text, panel, ended]);
  const tick = useCallback(() => { if (!sound || !audio.current) return; const ctx = audio.current; const osc = ctx.createOscillator(), gain = ctx.createGain(); osc.type = 'sine'; osc.frequency.setValueAtTime(330, ctx.currentTime); osc.frequency.exponentialRampToValueAtTime(130, ctx.currentTime + .065); gain.gain.setValueAtTime(.035, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.001, ctx.currentTime + .08); osc.connect(gain); gain.connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime + .09); }, [sound]);
  const next = useCallback(() => { if (panel || ended) return; tick(); if (count < frame.text.length) setCount(frame.text.length); else if(index === frames.length - 1) setEnded(true); else setIndex(i => move(i, 1, frames.length)); }, [panel, ended, tick, count, frame.text.length, index, frames.length]);
  useEffect(() => { const key = e => { if(panel || /BUTTON|A|INPUT/.test(e.target.tagName)) return; if(['ArrowRight',' ','Enter'].includes(e.key)) { e.preventDefault(); next(); } if(e.key === 'ArrowLeft' && !ended) { e.preventDefault(); setIndex(i => move(i,-1,frames.length)); } }; window.addEventListener('keydown',key); return () => window.removeEventListener('keydown',key); }, [next,panel,ended,frames.length]);
  useEffect(() => { if(panel) modal.current?.showModal(); else modal.current?.close(); }, [panel]);
  const restart = () => { setIndex(0); setCount(0); setEnded(false); setPanel(null); };
  const toggleSound = async () => { if(!audio.current) audio.current = new AudioContext(); await audio.current.resume(); setSound(s => !s); };
  return <main className={`novel voice-${frame.voice} scene-${frame.scene}`}>
    <div className="space" aria-hidden="true"><svg viewBox="0 0 1270 480" preserveAspectRatio="xMidYMid slice"><g fill="currentColor"><ellipse cx="125" cy="160" rx="28" ry="26" transform="rotate(35 125 160)"/><ellipse cx="394" cy="227" rx="43" ry="86" transform="rotate(28 394 227)"/><ellipse cx="387" cy="161" rx="13" ry="18"/><ellipse cx="1048" cy="273" rx="57" ry="114" transform="rotate(31 1048 273)"/><ellipse cx="1094" cy="211" rx="49" ry="38" transform="rotate(-26 1094 211)"/><ellipse cx="927" cy="134" rx="25" ry="26"/><ellipse cx="1254" cy="149" rx="25" ry="33"/><ellipse cx="70" cy="444" rx="42" ry="75" transform="rotate(35 70 444)"/><ellipse cx="234" cy="443" rx="31" ry="27"/><ellipse cx="369" cy="395" rx="14" ry="13"/><ellipse cx="354" cy="436" rx="12" ry="15"/><ellipse cx="1006" cy="454" rx="27" ry="34"/><ellipse cx="1093" cy="432" rx="34" ry="27" transform="rotate(-23 1093 432)"/><ellipse cx="811" cy="-3" rx="29" ry="57" transform="rotate(30 811 -3)"/><ellipse cx="496" cy="-14" rx="41" ry="38"/><ellipse cx="1063" cy="7" rx="20" ry="40" transform="rotate(20 1063 7)"/></g><path d="M227 -20C151 116 241 226 230 332Q218 430 162 466" fill="none" stroke="currentColor" strokeWidth="25"/></svg></div>
    <nav aria-label="Настройки"><button onClick={toggleSound} aria-pressed={sound} title="Звук переходов">{sound ? 'sound' : 'sound off'}</button><span>\</span><button onClick={() => setPanel('restart')}>restart</button><span>\</span><button onClick={() => setPanel('info')}>info</button></nav>
    <section className="dialogue-region" aria-label="Текст новеллы">
      <div className="dialogue" onClick={next}>
        {(ended || labels[frame.voice]) && <div className="name">{ended ? 'КОНЕЦ ФРАГМЕНТА' : labels[frame.voice]}</div>}
        {ended ? <div className="ending"><p>На этом обрывается рукопись.</p><button onClick={e => { e.stopPropagation(); restart(); }}>начать сначала ↗</button></div> : <><p className="text" aria-live="polite"><span className="sr-only">{frame.text}</span><span aria-hidden="true">{frame.text.slice(0,count)}<span className="unrevealed">{frame.text.slice(count)}</span></span></p>{frame.text.includes('чёрнухе*') && <small>* католит</small>}<button className="next" aria-label={count < frame.text.length ? 'Показать реплику целиком' : 'Следующая реплика'} onClick={e => { e.stopPropagation(); next(); }}><svg viewBox="0 0 46 20" aria-hidden="true"><path d="M2 11 42 10M31 3l12 7-12 6"/></svg></button></>}
      </div>
    </section>
    <dialog ref={modal} onCancel={() => setPanel(null)} onClick={e => {if(e.target===modal.current)setPanel(null);}}><div className="modal-content"><button className="close" onClick={() => setPanel(null)} aria-label="Закрыть">×</button><h1>{panel === 'restart' ? 'С НАЧАЛА?' : 'КСИВА'}</h1>{panel === 'restart' ? <><p>Текущее место чтения будет сброшено.</p><div className="actions"><button onClick={restart}>начать заново</button><button onClick={() => setPanel(null)}>продолжить</button></div></> : <><p>Одна в своём маленьком прекрасном катере.</p><p>Клик, пробел или → — дальше.<br/>Первое нажатие раскрывает реплику.<br/>← — предыдущая реплика.</p><p>Место чтения сохраняется в этом браузере.<br/>sound — звук переходов.</p><p className="muted">Сцена {frame.scene} / 5 · {index + 1} / {frames.length}<br/>Текст: «новелла_1». Шрифт: Hypermarket.</p></>}</div></dialog>
  </main>;
}
